version: "3"

services:
  db:
    image: 'postgres'
    ports:
      - '5432'
#    networks:
#      some_network:
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./django:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
    links:
      - db:db
#    networks:
#      some_network:
#  networks:
#    some_network: