version: "3"

services:
  db:
    image: 'postgres'
    ports:
      - '5432'
#    networks:
#      some_network:
  dj:
    container_name: dj
    build: django
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS=dev    links:
      - db:db
  ng:
    container_name: ng
    build: angular
    ports:
      - "8080:80"
#    networks:
#      some_network:
#  networks:
#    some_network: