# Generated by Django 2.1.4 on 2019-09-20 06:26

from django.db import migrations

def create_dummy_tasks(apps, schema_editor):
    Task = apps.get_model('todoapi', 'Task')

    Task(title='qqq', content='111').save()
    Task(title='www', content='222').save()
    Task(title='three', content='333').save()


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_tasks),
    ]
