# Generated by Django 2.1.4 on 2019-09-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0003_auth0user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
